language: r

sudo: false

cache: packages

before_install:
#  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
#  - chmod 755 ./travis-tool.sh
#  - ./travis-tool.sh bootstrap
   - apt-get install libgsl0-dev

#install:
#  - ./travis-tool.sh install_deps

#script: ./travis-tool.sh run_tests

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); coveralls()'
  - Rscript -e 'library(covr); codecov()'

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change